sudo: false
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
branches:
  only:
  - master
env:
  global:
    - DJANGO_SETTINGS_MODULE=test.testsettings
    - PYTHONPATH="."
  matrix:
    - DJANGO_DEP="django==2.1"
    - DJANGO_DEP="django==2.2"
    - DJANGO_DEP="git+https://github.com/django/django.git"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_DEP="git+https://github.com/django/django.git"
  allow_failures:
    - python: "3.6"
      env: DJANGO_DEP="git+https://github.com/django/django.git"
    - python: "3.7"
      env: DJANGO_DEP="git+https://github.com/django/django.git"
install:
  - pip install poetry
  - poetry install
  - poetry run pip install --upgrade pip
  - poetry run pip install "${DJANGO_DEP}"
script: poetry run django-admin.py test tests
