sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
  - master
env:
  global:
    - DJANGO_SETTINGS_MODULE=test_settings
    - PYTHONPATH="."
  matrix:
    - DJANGO_DEP="django==2.2"
    - DJANGO_DEP="django==3.0"
    - DJANGO_DEP="django==3.1"
    - DJANGO_DEP="git+https://github.com/django/django.git"
matrix:
  allow_failures:
    - env: DJANGO_DEP="git+https://github.com/django/django.git"
install:
  - pip install poetry
  - poetry install
  - poetry run pip install "${DJANGO_DEP}"
script: poetry run django-admin.py test tests
