name: django-fast-ratelimit

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: ["3.9", "3.10", "3.11", "3.12"]

        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - name: Install poetry
              run: python -m pip install poetry
            - name: Install package
              run: poetry install --only main,test
            - name: Run tox
              run: poetry run tox -s
            - name: Convert coverage
              run: poetry run coverage xml
            - name: Upload Coverage to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
